### ISSUE TITLE
Bombs when trying to CreateInstance() while debugging on iPhone on iOS 13

### ISSUE THREAD

**Issue by MichaelSafro** [Envoc/ZebraSDK#1]
The library compiles and is recognized by consuming project, however, it when trying to debug on iPhone (iOS 13.0, latest VS 2019 on both Windows and Mac), CreateInstance() call crashes app and sometimes crashes/freezes VS. Any ideas?

**Comment by MichaelSafro** [comment]
I actually think I figured the issue. The SDK currently only supports iOS 12.X not 13.X...

**Comment by svaldetero-envoc** [comment]
@MichaelSafro I had this issue too. You need to add the new iOS 13 Bluetooth permission.

    
    <key>NSBluetoothPeripheralUsageDescription</key>
    <string>Allow communication with the scanner.</string>

    
    <key>NSBluetoothAlwaysUsageDescription</key>
    <string>Allow communication with the scanner.</string>

**Comment by MichaelSafro** [comment]
Thanks a ton @svaldetero - Seth! I figured it was due to differences in between iOS versions, but did not know about the permission. I will try it.
